author: 'MrLotU'
author_url: 'https://github.com/MrLotU'
github_url: 'https://github.com/MrLotU/SwiftPrometheus'
github_file_prefix: 'https://github.com/MrLotU/SwiftPrometheus/tree/master/'
theme: 'fullwidth'
undocumented_text: ''
root_url: 'https://mrlotu.github.io/SwiftPrometheus/'